name: Build and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn clean package -DskipTests
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-war
          path: target/mvnwebapp.war
      
      - name: example
        run: echo "Hello runner testing2"
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          path: C:\Self-Hosted-NonService-Runner

      - name: Install or Update WinSW Service
        run: |
          # Set the service name
          $serviceName = "MavenWebApp"
          
          # Navigate to the directory where WinSW and your XML configuration are located
          cd C:\Self-Hosted-NonService-Runner
          
          # Check if the service is installed
          $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
          
          if ($service) {
              # Service is installed, check if it is running
              if ($service.Status -eq 'Running') {
                  Write-Host "Service is running. Stopping the service..."
                  Stop-Service -Name $serviceName -Force
              } else {
                  Write-Host "Service is installed but not running."
              }
              # Uninstall the service to ensure a clean state
              Write-Host "Uninstalling the existing service..."
              .\winsw.exe uninstall
          } else {
              Write-Host "Service is not installed."
          }
          
          # Install the service
          Write-Host "Installing the service..."
          .\winsw.exe install
          
          # Start the service
          Write-Host "Starting the service..."
          Start-Service -Name $serviceName
