name: Build and Deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: '0'
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-war
          path: target/mvnwebapp.war
      
      - name: example
        run: echo "Hello runner testing1"
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          path: C:\Self-Hosted-NonService-Runner
