on:
  push:
    branches:
      - master # or the name of your main branch
      - main

jobs:
  bash-example:
    runs-on: self-hosted
    steps:
      - name: Group of log lines
        shell: cmd
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::" 
