on:
  push:
    branches:
      - master # or the name of your main branch
      - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - name: example-step
        run: echo "Hello World!"
      - name: print-ENV
        run: "[System.Environment]::GetEnvironmentVariables()"
      - name: Use Command Prompt
        run: |
	  echo %PATH% 
	  echo %JAVA_HOME%
	  echo %MAVEN_HOME%
	  mvn --version
        shell: cmd
