name: build deployment
on:
  push:
    branches:
     - master
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-war
        path: target/mvnwebapp.war
  local-job:
    runs-on: self-hosted
    needs: build
    steps:
      - name: example
        run: echo "Hello runner testing3"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          path: C:\Users\AG6564\Self-Hosted-NonService-Runner
